import type { APIRoute } from 'astro';
// @ts-ignore -- pdfkit has no bundled types but the package is installed
import PDFDocument from 'pdfkit';

export const GET: APIRoute = async ({ url }) => {
  const params = url.searchParams;

  const businessName     = params.get('businessName')      || '[Business Name]';
  const state            = params.get('state')             || '[State]';
  const ownerName        = params.get('ownerName')         || '[Owner Name]';
  const businessAddress  = params.get('businessAddress')   || '[Address]';
  const activityType     = params.get('activityType')      || 'General Activities';
  const activityDesc     = params.get('activityDescription') || '';
  const specificRisks    = params.get('specificRisks')     || '';
  const minAge           = params.get('minAge')            || '18+';
  const emergencyContact = params.get('emergencyContact') === 'true';

  return new Promise<Response>((resolve) => {
    const doc = new PDFDocument({ margin: 60, size: 'LETTER' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(chunks);
      resolve(
        new Response(pdfBuffer, {
          status: 200,
          headers: {
            'Content-Type': 'application/pdf',
            'Content-Disposition': `attachment; filename="waiver-${businessName.replace(/\s+/g, '-').toLowerCase()}.pdf"`,
            'Content-Length': String(pdfBuffer.length),
          },
        })
      );
    });

    // ---- PDF Content ----

    // Header
    doc
      .fontSize(8)
      .fillColor('#6B7280')
      .text('Generated by WaiverMaker.com — Not Legal Advice', { align: 'center' })
      .moveDown(0.5);

    // Title
    doc
      .fontSize(18)
      .fillColor('#111827')
      .font('Helvetica-Bold')
      .text('LIABILITY WAIVER AND RELEASE OF LIABILITY', { align: 'center' })
      .moveDown(0.5);

    // Business info
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#111827')
      .text(businessName, { align: 'center' })
      .font('Helvetica')
      .fillColor('#374151')
      .text(businessAddress, { align: 'center' })
      .text(`Owner / Manager: ${ownerName}  |  State: ${state}`, { align: 'center' })
      .moveDown(0.8);

    // Divider
    doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor('#E5E7EB').stroke().moveDown(0.8);

    const bodyFont = 'Helvetica';
    const boldFont = 'Helvetica-Bold';
    const bodySize = 10;
    const bodyColor = '#374151';

    function section(title: string, body: string) {
      doc
        .font(boldFont).fontSize(bodySize).fillColor('#111827')
        .text(title)
        .font(bodyFont).fontSize(bodySize).fillColor(bodyColor)
        .text(body, { lineGap: 3 })
        .moveDown(0.6);
    }

    section(
      '1. PARTICIPANT INFORMATION',
      `I, the undersigned participant, wish to participate in ${activityType} activities provided by ${businessName}, located at ${businessAddress}, ${state}.`
    );

    section(
      '2. DESCRIPTION OF ACTIVITIES',
      activityDesc
        ? `The activities I will participate in include: ${activityDesc}`
        : `The activities I will participate in include ${activityType.toLowerCase()} activities as offered by ${businessName}.`
    );

    section(
      '3. ASSUMPTION OF RISK',
      `I understand and acknowledge that participation in ${activityType} activities involves inherent risks, dangers, and hazards, including but not limited to: ${specificRisks || 'physical injury, property damage, and other foreseeable and unforeseeable risks'}. I am voluntarily choosing to participate in these activities with full knowledge and understanding of the risks involved.`
    );

    section(
      '4. RELEASE OF LIABILITY',
      `In consideration of being permitted to participate in ${activityType} activities at ${businessName}, I hereby RELEASE, WAIVE, DISCHARGE, and COVENANT NOT TO SUE ${businessName}, its owners, officers, directors, employees, agents, contractors, and representatives (collectively "Released Parties") from any and all liability, claims, demands, actions, and causes of action whatsoever arising out of or related to any loss, damage, injury, or death that may be sustained by me while participating in any activity associated with ${businessName}, whether caused by the negligence of the Released Parties or otherwise, to the fullest extent permitted by the laws of the State of ${state}.`
    );

    section(
      '5. INDEMNIFICATION',
      `I agree to indemnify and hold harmless the Released Parties from any loss, liability, damage, or cost, including reasonable attorney\'s fees, that they may incur due to my participation in ${activityType} activities at ${businessName}.`
    );

    section(
      '6. MEDICAL AUTHORIZATION',
      `In the event of an emergency in which I am unable to give consent, I authorize ${businessName} and its agents to seek emergency medical treatment on my behalf. I acknowledge that I am solely responsible for all medical expenses incurred.`
    );

    if (emergencyContact) {
      doc
        .font(boldFont).fontSize(bodySize).fillColor('#111827')
        .text('7. EMERGENCY CONTACT')
        .font(bodyFont).fontSize(bodySize).fillColor(bodyColor)
        .text('Emergency Contact Name: _______________________________  Relationship: _______________')
        .text('Emergency Contact Phone: _______________________________  Alternate Phone: ___________')
        .moveDown(0.6);
    }

    const nextSection = emergencyContact ? '8' : '7';
    section(
      `${nextSection}. PARTICIPANT ELIGIBILITY`,
      `I confirm that I meet the minimum age requirement of ${minAge} to participate in activities at ${businessName}. If I am under the required age, I confirm that I have obtained appropriate parental or guardian consent.`
    );

    section(
      `${parseInt(nextSection) + 1}. GOVERNING LAW`,
      `This Liability Waiver and Release shall be governed by and construed in accordance with the laws of the State of ${state}. If any provision of this waiver is found to be unenforceable, the remaining provisions shall continue in full force and effect.`
    );

    section(
      `${parseInt(nextSection) + 2}. ACKNOWLEDGMENT`,
      'I have carefully read this Liability Waiver and Release, fully understand its contents, and I am aware that this is a release of liability. I sign this document of my own free will.'
    );

    // Signature lines
    doc.moveDown(0.5);
    doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor('#E5E7EB').stroke().moveDown(0.8);

    doc
      .font(boldFont).fontSize(bodySize).fillColor('#111827')
      .text('SIGNATURES', { align: 'center' })
      .moveDown(0.6);

    doc
      .font(bodyFont).fontSize(bodySize).fillColor(bodyColor)
      .text('Participant Signature: ________________________________     Date: ___________________')
      .moveDown(0.4)
      .text('Printed Name: ________________________________')
      .moveDown(0.8);

    doc
      .text('Parent / Guardian Signature (if minor): ________________________________     Date: ___________________')
      .moveDown(0.4)
      .text('Printed Name: ________________________________')
      .moveDown(0.8);

    // Footer disclaimer
    doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor('#E5E7EB').stroke().moveDown(0.6);
    doc
      .fontSize(7)
      .fillColor('#9CA3AF')
      .text(
        'This waiver was generated by WaiverMaker.com and is provided for informational purposes only. It does not constitute legal advice. Consult a licensed attorney in your jurisdiction to ensure this document meets your specific legal needs. WaiverMaker.com is not responsible for the legal sufficiency of this document.',
        { align: 'center', lineGap: 2 }
      );

    doc.end();
  });
};

export const POST: APIRoute = async ({ request }) => {
  const body = await request.json().catch(() => ({}));
  const params = new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)]));
  const fakeUrl = new URL(`http://localhost/api/generate-pdf?${params.toString()}`);
  return GET({ url: fakeUrl, request, params: {}, props: {}, redirect: () => new Response(null, { status: 302 }), rewrite: async () => new Response(null, { status: 200 }), locals: {} } as any);
};
